# Generated by Django 5.0.3 on 2024-04-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('catagory', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
